FlaskMaster/Chapter13/webapp/babel/controllers.py
from flask import Blueprint, session, redirect, url_for

babel_blueprint = Blueprint(
    'babel',
    __name__,
    url_prefix="/babel"
)


@babel_blueprint.route('/<string:locale>')
def index(locale):
    session['locale'] = locale
    return redirect(url_for('blog.home'))

FlaskMaster/Chapter13/webapp/blog/controllers.py
import datetime
from sqlalchemy import desc, func
from flask import (
    render_template,
    Blueprint,
    flash,
    redirect,
    url_for,
    session,
    current_app,
    abort,
    request,
    get_flashed_messages
)
from flask_login import login_required, current_user
from .models import db, Post, Tag, Comment, tags
from .forms import CommentForm, PostForm
from .. import cache
from ..auth.models import User
from ..auth import has_role

blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    messages = str(hash(frozenset(get_flashed_messages())))
    if current_user.is_authenticated:
        roles = str(current_user.roles)
    else:
        roles = ""
    return (path + args + roles + session.get('locale', '') + messages).encode('utf-8')


@cache.cached(timeout=7200, key_prefix='sidebar_data')
def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(tags).group_by(Tag).order_by(desc('total')).limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page,
                                                                   current_app.config.get('POSTS_PER_PAGE', 10),
                                                                   False)
    recent, top_tags = sidebar_data()

    return render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.user_id = current_user.id
        new_post.text = form.text.data
        new_post.youtube_id = form.youtube_id.data
        db.session.add(new_post)
        db.session.commit()
        flash('Post added', 'info')
        return redirect(url_for('.post', post_id=new_post.id))
    return render_template('new.html', form=form)


@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    # We want admins to be able to edit any post
    if current_user.id == post.user.id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.youtube_id = form.youtube_id.data
            post.text = form.text.data
            post.publish_date = datetime.datetime.now()
            db.session.merge(post)
            db.session.commit()
            flash('Post edited', 'info')
            return redirect(url_for('.post', post_id=post.id))
        form.title.data = post.title
        form.youtube_id.data = post.youtube_id
        form.text.data = post.text
        return render_template('edit.html', form=form, post=post)
    abort(403)


@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash('Error adding your comment: %s' % str(e), 'error')
            db.session.rollback()
        else:
            flash('Comment added', 'info')
        return redirect(url_for('blog.post', post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )


@blog_blueprint.route('/tag/<string:tag_name>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/user/<string:username>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

FlaskMaster/Chapter13/webapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    <div class="row row-lg-4">
        <div class="col">
            {% block head %}
            {% include 'head.html' %}
            {% endblock %}
        </div>
    </div>
    {% include 'messages.html' %}
    {% block body %}
    <div class="row">
        <div class="col-lg-9">
            {% block leftbody %}
            {% endblock %}
        </div>
        <div class="col-lg-3 rounded">
            {% block rightbody %}
            {% include 'rightbody.html' %}
            {% endblock %}
        </div>
    </div>
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
{% block js %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

FlaskMaster/Chapter13/webapp/templates/footer.html
<div class="row">
    Hands on Web development with Flask - 2018
</div>

FlaskMaster/Chapter13/webapp/templates/head.html
<div class="container bg-info rounded">
    <center>
    <i class="fas fa-comments fa-5x"></i>
    <h1><a class="text-white" href="{{ url_for('blog.home') }}">My Blog</a></h1>
    <p>{{_('Welcome to this Blog')}}</p>
    </center>
</div>

FlaskMaster/Chapter13/webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a class="page-link" href="">{{ page }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item">
            <a class="page-link">…</a>
        <li>
            {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}

{% macro render_posts(posts, pagination=True) %}
    {% if pagination %}
        {% set _posts = posts.items %}
    {% else %}
        {% set _posts = posts %}
    {% endif %}

    {% for post in _posts %}
        <div >
            <h1>
                <a class="text-dark" href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
            </h1>
        </div>
        <div class="row">
            <div class="col">
                {{ post.text | truncate(500) | safe }}
                <a href="{{ url_for('blog.post', post_id=post.id) }}">{{_('Read More')}}</a>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

FlaskMaster/Chapter13/webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

FlaskMaster/Chapter13/webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('blog.home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated and current_user.has_role('poster') %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.new_post')}}">{{_('New Post')}}<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.has_role('admin') %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.index')}}">Admin<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                    Lang
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{url_for('babel.index', locale='en')}}">en</a>
                    <a class="dropdown-item" href="{{url_for('babel.index', locale='pt')}}">pt</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('blog.home')}}"></a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#user">
                    <i class="fa fa-fw fa-sign-out"></i>{{ current_user }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">
                <i class="fa fa-fw fa-sign-out"></i>{{_('Logout')}}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">
                <i class="fa fa-fw fa-sign-in"></i>{{_('Login')}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.register')}}">
                <i class="fa fa-fw fa-sign-in"></i>{{_('Register')}}</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>