FlaskMaster/Chapter13/webapp/blog/models.py
import datetime
from .. import db

tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)


class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    text = db.Column(db.Text(), nullable=False)
    publish_date = db.Column(db.DateTime(), default=datetime.datetime.now)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    youtube_id = db.Column(db.String(255))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')
    tags = db.relationship('Tag', secondary=tags,
                           backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Post '{}'>".format(self.title)


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    text = db.Column(db.Text(), nullable=False)
    date = db.Column(db.DateTime(), default=datetime.datetime.now)
    post_id = db.Column(db.Integer(), db.ForeignKey('post.id'))

    def __repr__(self):
        return "<Comment '{}'>".format(self.text[:15])


class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255), nullable=False, unique=True)

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Tag '{}'>".format(self.title)


class Reminder(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    date = db.Column(db.DateTime())
    email = db.Column(db.String(255))
    text = db.Column(db.Text())

    def __repr__(self):
        return "<Reminder '{}'>".format(self.text[:20])

FlaskMaster/Chapter13/webapp/blog/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length


class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])


class PostForm(Form):
    title = StringField('Title', [DataRequired(), Length(max=255)])
    youtube_id = StringField('Youtube video id', [Length(max=255)])
    text = TextAreaField('Content', [DataRequired()])

FlaskMaster/Chapter13/webapp/api/blog/controllers.py
from flask import abort, current_app, jsonify
from flask_restful import Resource, fields, marshal_with
from flask_jwt_extended import jwt_required, get_jwt_identity
from webapp.blog.models import db, Post, Tag, Reminder
from webapp.auth.models import User
from .parsers import (
    post_get_parser,
    post_post_parser,
    post_put_parser,
    reminder_post_parser
)
from .fields import HTMLField


nested_tag_fields = {
    'id': fields.Integer(),
    'title': fields.String()
}

post_fields = {
    'id': fields.Integer(),
    'author': fields.String(attribute=lambda x: x.user.username),
    'title': fields.String(),
    'text': HTMLField(),
    'tags': fields.List(fields.Nested(nested_tag_fields)),
    'publish_date': fields.DateTime(dt_format='iso8601')
}

reminder_fields = {
    'id': fields.Integer(),
    'email': fields.String(),
    'text': fields.String(),
}


def add_tags_to_post(post, tags_list):
    for item in tags_list:
        tag = Tag.query.filter_by(title=item).first()

        # Add the tag if it exists. If not, make a new tag
        if tag:
            post.tags.append(tag)
        else:
            new_tag = Tag(item)
            post.tags.append(new_tag)


class ReminderApi(Resource):
    @marshal_with(reminder_fields)
    @jwt_required
    def get(self, reminder_id=None):
        print("CANAS")
        if reminder_id:
            reminder = Reminder.query.get(reminder_id)
            if not reminder:
                abort(404)
            return reminder
        else:
            reminders = Reminder.query.all()
            return reminders

    @jwt_required
    def post(self, reminder_id=None):
        if reminder_id:
            abort(400)
        else:
            args = reminder_post_parser.parse_args(strict=True)
            new_reminder = Reminder()
            new_reminder.email = args['email']
            new_reminder.text = args['text']
            db.session.add(new_reminder)
            db.session.commit()
            return {'id': new_reminder.id}, 201


class PostApi(Resource):
    @marshal_with(post_fields)
    @jwt_required
    def get(self, post_id=None):
        if post_id:
            post = Post.query.get(post_id)
            if not post:
                abort(404)
            return post
        else:
            args = post_get_parser.parse_args()
            page = args['page'] or 1

            if args['user']:
                user = User.query.filter_by(username=args['user']).first()
                if not user:
                    abort(404)

                posts = user.posts.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config['POSTS_PER_PAGE'])
            else:
                posts = Post.query.order_by(
                    Post.publish_date.desc()
                ).paginate(page, current_app.config['POSTS_PER_PAGE'])

            return posts.items

    @jwt_required
    def post(self):
        args = post_post_parser.parse_args(strict=True)
        new_post = Post(args['title'])
        new_post.user_id = get_jwt_identity()
        new_post.text = args['text']

        if args['tags']:
            add_tags_to_post(new_post, args['tags'])

        db.session.add(new_post)
        db.session.commit()
        return {'id': new_post.id}, 201

    @jwt_required
    def put(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        args = post_put_parser.parse_args(strict=True)
        if get_jwt_identity() != post.user_id:
            abort(403)
        if args['title']:
            post.title = args['title']
        if args['text']:
            post.text = args['text']
        if args['tags']:
            print("Tags %s" % args['tags'])
            add_tags_to_post(post, args['tags'])

        db.session.merge(post)
        db.session.commit()
        return {'id': post.id}, 201

    @jwt_required
    def delete(self, post_id=None):
        if not post_id:
            abort(400)
        post = Post.query.get(post_id)
        if not post:
            abort(404)
        if get_jwt_identity() != post.user_id:
            abort(401)

        db.session.delete(post)
        db.session.commit()
        return "", 204

FlaskMaster/Chapter13/webapp/blog/__init__.py
from sqlalchemy import event
from .models import Reminder
from .tasks import on_reminder_save


def create_module(app, **kwargs):
    event.listen(Reminder, 'after_insert', on_reminder_save)
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

FlaskMaster/Chapter13/webapp/blog/controllers.py
import datetime
from sqlalchemy import desc, func
from flask import (
    render_template,
    Blueprint,
    flash,
    redirect,
    url_for,
    session,
    current_app,
    abort,
    request,
    get_flashed_messages
)
from flask_login import login_required, current_user
from .models import db, Post, Tag, Comment, tags
from .forms import CommentForm, PostForm
from .. import cache
from ..auth.models import User
from ..auth import has_role

blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    messages = str(hash(frozenset(get_flashed_messages())))
    if current_user.is_authenticated:
        roles = str(current_user.roles)
    else:
        roles = ""
    return (path + args + roles + session.get('locale', '') + messages).encode('utf-8')


@cache.cached(timeout=7200, key_prefix='sidebar_data')
def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(tags).group_by(Tag).order_by(desc('total')).limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def home(page=1):
    posts = Post.query.order_by(Post.publish_date.desc()).paginate(page,
                                                                   current_app.config.get('POSTS_PER_PAGE', 10),
                                                                   False)
    recent, top_tags = sidebar_data()

    return render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
@has_role('poster')
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.user_id = current_user.id
        new_post.text = form.text.data
        new_post.youtube_id = form.youtube_id.data
        db.session.add(new_post)
        db.session.commit()
        flash('Post added', 'info')
        return redirect(url_for('.post', post_id=new_post.id))
    return render_template('new.html', form=form)


@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    # We want admins to be able to edit any post
    if current_user.id == post.user.id:
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.youtube_id = form.youtube_id.data
            post.text = form.text.data
            post.publish_date = datetime.datetime.now()
            db.session.merge(post)
            db.session.commit()
            flash('Post edited', 'info')
            return redirect(url_for('.post', post_id=post.id))
        form.title.data = post.title
        form.youtube_id.data = post.youtube_id
        form.text.data = post.text
        return render_template('edit.html', form=form, post=post)
    abort(403)


@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        try:
            db.session.add(new_comment)
            db.session.commit()
        except Exception as e:
            flash('Error adding your comment: %s' % str(e), 'error')
            db.session.rollback()
        else:
            flash('Comment added', 'info')
        return redirect(url_for('blog.post', post_id=post_id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )


@blog_blueprint.route('/tag/<string:tag_name>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )


@blog_blueprint.route('/user/<string:username>')
@cache.cached(timeout=60, key_prefix=make_cache_key)
def posts_by_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

FlaskMaster/Chapter13/webapp/templates/blog/edit.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>Edit Post</h1>
        </div>
    </div>

<div class="row">
    <form method="POST" action="{{ url_for('.edit_post', id=post.id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
            {% for e in form.title.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.youtube_id.label }}
            {% if form.youtube_id.errors %}
            {% for e in form.youtube_id.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.youtube_id(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
            {% for e in form.text.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>
    {% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

FlaskMaster/Chapter13/webapp/templates/blog/home.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}
{% block title %}Home{% endblock %}
{% block leftbody %}
{{ macros.render_posts(posts) }}
{{ macros.render_pagination(posts, 'blog.home') }}
{% endblock %}

FlaskMaster/Chapter13/webapp/templates/blog/new.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>Create a New Post</h1>
        </div>
    </div>

<div class="row">
    <form method="POST" action="{{ url_for('.new_post') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
            {% for e in form.title.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.youtube_id.label }}
            {% if form.youtube_id.errors %}
            {% for e in form.youtube_id.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.youtube_id(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
            {% for e in form.text.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>
    {% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

FlaskMaster/Chapter13/webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
    <div class="row shadow-sm">
        <div class="col-lg-6">
            <p>Written By <a href="{{ url_for('blog.posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a> on {{ post.publish_date }}</p>
        </div>
        <div class="col-lg-6">
            <p class="text-right"> Tags: {% for tag in tags %}
                <a href="{{ url_for('blog.posts_by_tag', tag_name=tag.title) }}">{{tag.title}}</a>
                {% endfor %}
            </p>
        </div>
    </div>
    {% if post.youtube_id %}
    <div class="row">
        <div class="col">
            {{ youtube(post.youtube_id) | safe }}
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col">
            {{ post.text | safe }}
        </div>
    </div>
    {% if current_user.id == post.user_id %}
    <div class="col-lg-2">
        <a href="{{ url_for('.edit_post', id=post.id) }}" class="btn
       btn-primary">Edit</a>
    </div>
    {% endif %}
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>New Comment:</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.name.label }}
                    {% if form.name.errors %}
                    {% for e in form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.name(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.text(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Add Comment">
            </form>
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>Comments ({{ comments | length }})</h4>
        </div>
    </div>
    <div class="row p-2">
        <div class="col">
            {% if comments | length == 0 %}
            <p>There are no comments for this post.</p>
            {% else %}
            {% for comment in comments %}
            <div class="shadow-sm p-2">
                <dt>By: {{ comment.name }} on {{ comment.date }}</dt>
                <dd>{{ comment.text }}</dd>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

FlaskMaster/Chapter13/webapp/templates/blog/rightbody.html
<div class="row">
    <div class="col">
        <h5>{{_('Recent Posts')}}</h5>
    </div>
</div>
<ul class="list-group">
    {% for post in recent %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
<div class="row">
    <div class="col">
        <h5>{{_('Popular Tags')}}</h5>
    </div>
</div>
<ul class="list-group">
    {% for tag in top_tags %}
    <li class="list-group-item"
    ><a href="{{ url_for('blog.posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
    {% endfor %}
</ul>

FlaskMaster/Chapter13/webapp/templates/blog/tag.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

FlaskMaster/Chapter13/webapp/templates/blog/user.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}